BEGIN TRANSACTION;
INSERT INTO "item" VALUES (1,'Racine',NULL);
INSERT INTO "item" VALUES (2,'Fia',1);
INSERT INTO "item" VALUES (3,'Fig',2);
INSERT INTO "item" VALUES (4,'Infres 12',2);
INSERT INTO "item" VALUES (5,'Infres 11',2);
INSERT INTO "item" VALUES (7,'Commun',4);
INSERT INTO "item" VALUES (8,'dl',4);
INSERT INTO "item" VALUES (9,'sr',4);
INSERT INTO "item" VALUES (10,'S5',8);
INSERT INTO "item" VALUES (11,'S6',8);
INSERT INTO "item" VALUES (12,'module 1',10);
INSERT INTO "item" VALUES (13,'module 2',10);
INSERT INTO "item" VALUES (14,'module 1',11);
INSERT INTO "item" VALUES (15,'module 2',11);
INSERT INTO "item" VALUES (16,'cours 1',14);
INSERT INTO "item" VALUES (17,'cours 2 ',14);
INSERT INTO "item" VALUES (18,'cours 1',10);
INSERT INTO "item" VALUES (19,'cours 3 ',10);
COMMIT;
